// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow to generate FAQs for a given service.
 *
 * - generateServiceFaqs - A function that generates FAQs for a service.
 * - GenerateServiceFaqsInput - The input type for the generateServiceFaqs function.
 * - GenerateServiceFaqsOutput - The return type for the generateServiceFaqs function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateServiceFaqsInputSchema = z.object({
  serviceName: z.string().describe('The name of the service to generate FAQs for.'),
  serviceDescription: z.string().describe('A detailed description of the service.'),
});

export type GenerateServiceFaqsInput = z.infer<typeof GenerateServiceFaqsInputSchema>;

const GenerateServiceFaqsOutputSchema = z.object({
  faqPage: z.string().describe('The generated FAQ page content for the service.'),
});

export type GenerateServiceFaqsOutput = z.infer<typeof GenerateServiceFaqsOutputSchema>;

export async function generateServiceFaqs(input: GenerateServiceFaqsInput): Promise<GenerateServiceFaqsOutput> {
  return generateServiceFaqsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateServiceFaqsPrompt',
  input: {schema: GenerateServiceFaqsInputSchema},
  output: {schema: GenerateServiceFaqsOutputSchema},
  prompt: `You are an expert in creating FAQ pages for services.

  Generate a comprehensive FAQ page for the following service, addressing common questions and concerns that potential customers may have.

  Service Name: {{{serviceName}}}
  Service Description: {{{serviceDescription}}}

  The FAQ page should be well-organized, easy to read, and provide informative answers.
  Each question should be clear and concise, and the answers should be thorough and helpful.
  Focus on the benefits, considerations, and key aspects of the service.
  Do not include any introductory or concluding sentences that are not part of a question or answer.
  Do not make up questions or answers, only use questions that a customer might actually ask.
  Format the FAQ page using markdown.
  `,
});

const generateServiceFaqsFlow = ai.defineFlow(
  {
    name: 'generateServiceFaqsFlow',
    inputSchema: GenerateServiceFaqsInputSchema,
    outputSchema: GenerateServiceFaqsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
